# TODO - Need a way to automatically re-key when the value of npk is changed.

# For new installations generate a new secrete key by running the following
# commands from within a Python shell:
#     import nacl.secret
#     import nacl.utils
#     from base64 import standard_b64encode as enc
#     enc(nacl.utils.random(nacl.secret.SecretBox.KEY_SIZE))
#
#     The value generated will look like:
#     b'62vfquuiXd9GU16mHZs+j7ipNebp148SgX0Odc+GyXk='
#
# Cut and paste the value generated by the commands listed above into 
# the line below as the new value for nsk_b64
#
# nacl secret key  DO NOT DIVULGE
nsk_b64 = [PASTE NEW VALUE HERE] 

# TODO - Move these things to the config.py file
#
# ########### JWT Settings ##############
#
fop_jose_id = ''
fopdcw_jose_id = ''
hmac_secret_key = ''
